version: '2'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    privileged: true
    ports:
      - "81:80"
    environment:
      ENABLE_IPV6: "true"
      DEFAULT_HOST: redmine
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy.conf:/etc/nginx/proxy.conf:ro

  redmine:
    image: redmine
    privileged: true
    ports:
      - 80:3000
    environment:
      REDMINE_DB_MYSQL: database
      REDMINE_DB_PASSWORD: secret
      VIRTUAL_HOST: redmine
    volumes:
      - ./volume-redmine/plugins:/usr/src/redmine/plugins
      - ./volume-redmine/files:/usr/src/redmine/files
      - ./wait-for-plugins.sh:/wait-for-plugins:rw
      - ./configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./volume-redmine/var/log/redmine/:/usr/src/redmine/log/
    extra_hosts:
      - "smtpserver:${SMTP_SERVER}"
    entrypoint: /wait-for-plugins
    command: ["rails", "server", "-b", "0.0.0.0"]
    depends_on:
      - database
    restart: always

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: redmine
    volumes:
      - data-volume:/var/lib/mysql
    restart: always

  tool:
    build: .
    volumes:
      - plugins:/redmine/plugins
      - files:/redmine/files
      - ./install-plugins.sh:/install-plugins:ro
    command: /install-plugins

volumes:
  data-volume:
  files:
  plugins:
